// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMHux1EHEHb3SgyqNWMLqf1XxClXj0iGw',
    appId: '1:826495799815:web:77ddbcd3d5aa64701ad0a2',
    messagingSenderId: '826495799815',
    projectId: 'streamix-30880',
    authDomain: 'streamix-30880.firebaseapp.com',
    storageBucket: 'streamix-30880.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq16ilKKCbV-2tqcCEAh7YPwwMjbqVOzU',
    appId: '1:826495799815:android:2405a63c60fb8a2d1ad0a2',
    messagingSenderId: '826495799815',
    projectId: 'streamix-30880',
    storageBucket: 'streamix-30880.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYHGn2aR3C4-Hop7TJdkf8mSFPLo7XNn0',
    appId: '1:826495799815:ios:f2fd6c2dc1cac8181ad0a2',
    messagingSenderId: '826495799815',
    projectId: 'streamix-30880',
    storageBucket: 'streamix-30880.firebasestorage.app',
    iosBundleId: 'com.example.streamnexadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYHGn2aR3C4-Hop7TJdkf8mSFPLo7XNn0',
    appId: '1:826495799815:ios:f2fd6c2dc1cac8181ad0a2',
    messagingSenderId: '826495799815',
    projectId: 'streamix-30880',
    storageBucket: 'streamix-30880.firebasestorage.app',
    iosBundleId: 'com.example.streamnexadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMHux1EHEHb3SgyqNWMLqf1XxClXj0iGw',
    appId: '1:826495799815:web:47a07ec4df0196021ad0a2',
    messagingSenderId: '826495799815',
    projectId: 'streamix-30880',
    authDomain: 'streamix-30880.firebaseapp.com',
    storageBucket: 'streamix-30880.firebasestorage.app',
  );
}
